#nelmio_api_doc:
#    documentation:
#        info:
#            title: My App
#            description: This is an awesome app!
#            version: 1.0.0
#    areas: # to filter documented areas
#        path_patterns:
#            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc

nelmio_api_doc:
    documentation:
        info:
            title: API
            version: 1.0.0
    areas:
        default:
            path_patterns: [ ^/api ]
