#controllers:
#    resource: ../../src/Controller/
#    type: attribute

kernel:
    resource: ../../src/Kernel.php
    type: attribute

order:
    resource: ../../src/Modules/Order/Controller/
    type: attribute

common:
    resource: ../../src/Modules/Common/Controller/
    type: attribute

user:
    resource: ../../src/Modules/User/Controller/
    type: attribute

search:
    resource: ../../src/Modules/Search/Controller/
    type: attribute
